version: 2

project_name: md2obs

builds:
  - id: md2obs
    main: ./cmd/md2obs
    binary: md2obs

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm64

    flags:
      - -trimpath

    ldflags:
      - >-
        -s -w
        -X main.version={{ .Version }}
        -X main.commit={{ .Commit }}

archives:
  - id: default

    formats:
      - tar.gz

    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

    files:
      - README.md
      - LICENSE
      - THIRD_PARTY_NOTICES.md

checksum:
  name_template: checksums.txt

changelog:
  use: github-native
